apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: aqara-wiki
    qcloud-app: aqara-wiki
    app: aqara-wiki
  name: aqara-wiki
  namespace: zzds-dev
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: aqara-wiki
      qcloud-app: aqara-wiki
      app: aqara-wiki
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: aqara-wiki
        qcloud-app: aqara-wiki
        app: aqara-wiki
    spec:
      containers:
      - image: __IMAGE_TAG__
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 5
          initialDelaySeconds: 90
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        name: aqara-wiki
        ports:
        - containerPort: 80
          name: tcp-80
          protocol: TCP
        readinessProbe:
          failureThreshold: 10
          initialDelaySeconds: 15
          periodSeconds: 15
          successThreshold: 1
          tcpSocket:
            port: 80
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
