apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: aqara-wiki
    qcloud-app: aqara-wiki
    app: aqara-wiki
  name: aqara-wiki
  namespace: zzds-dev 
spec:
  ports:
  - name: 80-http
    port: 80
  selector:
    k8s-app: aqara-wiki
    qcloud-app: aqara-wiki
    app: aqara-wiki
  type: NodePort
